'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { RefreshCw, Sparkles, ArrowLeft } from 'lucide-react';
import { PDFDownloadButton } from '@/components/pdf/PDFDownloadButton';
import toast from 'react-hot-toast';
import { api, Assignment, GeneratedPaper } from '../../../../lib/api';
import { useWebSocket } from '../../../../hooks/useWebSocket';
import { OutputPageSkeleton, GenerationSkeleton } from '../../../../components/ui/Skeleton';

const GENERATION_TOAST_ID = 'generation-toast';

function GeneratedByBadge({
  provider,
  usedFallback,
}: {
  provider?: string;
  usedFallback?: boolean;
}) {
  if (!provider && !usedFallback) return null;

  const label =
    usedFallback
      ? 'Generated by AI'
      : provider === 'gemini'
        ? 'Generated by Gemini AI'
        : provider === 'openai'
          ? 'Generated by OpenAI'
          : 'Generated by AI';

  const isGemini = !usedFallback && provider === 'gemini';

  return (
    <span
      className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold ${
        isGemini
          ? 'bg-green-50 text-green-700'
          : 'bg-gray-100 text-gray-700'
      }`}
    >
      <Sparkles size={12} />
      {label}
    </span>
  );
}

function DifficultyBadge({ difficulty }: { difficulty: string }) {
  const colors: Record<string, string> = {
    easy: 'bg-green-100 text-green-700',
    medium: 'bg-yellow-100 text-yellow-700',
    hard: 'bg-red-100 text-red-700',
  };
  return (
    <span
      className={`rounded-full px-2 py-0.5 text-xs font-medium capitalize ${
        colors[difficulty] || 'bg-gray-100 text-gray-600'
      }`}
    >
      {difficulty}
    </span>
  );
}

function TypeTag({ type }: { type: string }) {
  const labels: Record<string, string> = {
    mcq: 'MCQ',
    short_answer: 'Short Answer',
    long_answer: 'Long Answer',
  };
  return (
    <span className="text-[11px] font-medium px-2 py-0.5 rounded bg-gray-100 text-gray-600">
      {labels[type] || type}
    </span>
  );
}

function estimateRemainingSeconds(progress: number, startedAt: number): number | null {
  if (progress <= 5) return null;
  const elapsedMs = Date.now() - startedAt;
  const estimatedTotalMs = (elapsedMs / progress) * 100;
  const remainingMs = estimatedTotalMs - elapsedMs;
  return Math.max(1, Math.ceil(remainingMs / 1000));
}

export default function AssignmentOutputPage() {
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;

  const [assignment, setAssignment] = useState<Assignment | null>(null);
  const [paper, setPaper] = useState<GeneratedPaper | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [jobId, setJobId] = useState<string | null>(null);
  const generationStartRef = useRef<number | null>(null);

  const SCHOOL_NAME = 'Delhi Public School, Sector-4, Bokaro';
  const [, setTick] = useState(0);

  const ws = useWebSocket(id);

  const loadData = useCallback(async () => {
    try {
      const res = await api.getAssignment(id);
      setAssignment(res.data.assignment);
      setPaper(res.data.paper);
    } catch (err) {
      console.error(err);
      toast.error('Failed to load assignment');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  useEffect(() => {
    if (ws.paperId && !ws.isGenerating) {
      loadData();
      toast.dismiss(GENERATION_TOAST_ID);
      toast.success('Question paper generated successfully!');
    }
  }, [ws.paperId, ws.isGenerating, loadData]);

  const isGenerating =
    assignment?.status === 'generating' || ws.isGenerating || regenerating;

  useEffect(() => {
    if (isGenerating && !generationStartRef.current) {
      generationStartRef.current = Date.now();
      toast.loading('AI is generating questions...', { id: GENERATION_TOAST_ID });
    }
    if (!isGenerating) {
      generationStartRef.current = null;
    }
  }, [isGenerating]);

  useEffect(() => {
    if (!isGenerating) return;
    const interval = setInterval(() => setTick((t) => t + 1), 1000);
    return () => clearInterval(interval);
  }, [isGenerating]);

  useEffect(() => {
    if (ws.error) {
      toast.dismiss(GENERATION_TOAST_ID);
      toast.error('Generation failed. Please try again.');
    }
  }, [ws.error]);

  const handleRegenerate = async () => {
    setRegenerating(true);
    ws.reset();
    generationStartRef.current = Date.now();
    toast.loading('AI is generating questions...', { id: GENERATION_TOAST_ID });
    try {
      const res = await api.startGeneration(id, true);
      setJobId(res.jobId);
      setAssignment((a) => (a ? { ...a, status: 'generating' } : a));
      setPaper(null);
    } catch (err) {
      console.error(err);
      toast.dismiss(GENERATION_TOAST_ID);
      toast.error('Generation failed. Please try again.');
    } finally {
      setRegenerating(false);
    }
  };

  const provider = ws.llmUsed || assignment?.llmUsed;
  const usedFallback = ws.usedFallback;
  const progress = ws.progress || (isGenerating ? 5 : 0);
  const eta =
    isGenerating && generationStartRef.current
      ? estimateRemainingSeconds(progress, generationStartRef.current)
      : null;

  if (loading) {
    return <OutputPageSkeleton />;
  }

  if (!assignment) {
    return (
      <div className="text-center py-20">
        <p className="text-gray-600">Assignment not found</p>
        <button onClick={() => router.push('/')} className="mt-4 text-sm underline">
          Back to home
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <button
        onClick={() => router.push('/')}
        className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900 mb-6"
      >
        <ArrowLeft size={16} />
        Back to assignments
      </button>

      <div className="flex flex-wrap items-start justify-between gap-4 mb-2">
        <div className="flex-1 min-w-0">
          <h1 className="text-2xl font-bold text-gray-900">{assignment.title}</h1>
          <p className="text-gray-500 mt-1">
            {assignment.subject} · Grade {assignment.gradeLevel} · {assignment.totalMarks}{' '}
            marks · {assignment.duration} min
          </p>
        </div>
        <div className="flex items-center gap-2 flex-shrink-0">
          {paper && paper.sections.length > 0 && (
            <PDFDownloadButton
              assessment={{
                title: assignment.title,
                sections: paper.sections,
                totalMarks: paper.metadata.totalMarks,
                duration: assignment.duration,
              }}
              schoolName={SCHOOL_NAME}
              subject={assignment.subject}
              grade={assignment.gradeLevel}
              disabled={isGenerating}
            />
          )}
          <button
            onClick={handleRegenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium hover:bg-gray-50 disabled:opacity-50"
          >
            <RefreshCw size={14} className={isGenerating ? 'animate-spin' : ''} />
            Regenerate
          </button>
        </div>
      </div>

      {(paper?.status === 'completed' || assignment.llmUsed || provider) && (
        <div className="mb-8">
          <GeneratedByBadge provider={provider} usedFallback={usedFallback} />
        </div>
      )}

      {isGenerating && (
        <div className="mb-8">
          <div className="bg-white border border-gray-200 rounded-xl p-6 mb-4">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-5 h-5 border-2 border-orange-500 border-t-transparent rounded-full animate-spin" />
              <span className="font-medium text-gray-900">Generating question paper...</span>
            </div>
            <div className="w-full bg-gray-100 rounded-full h-2 mb-2">
              <div
                className="bg-orange-500 h-2 rounded-full transition-all duration-500"
                style={{ width: `${progress}%` }}
              />
            </div>
            <p className="text-sm text-gray-500">{ws.stage || 'Starting...'}</p>
            {eta !== null && (
              <p className="text-sm text-gray-400 mt-1">
                Estimated time remaining: ~{eta} seconds
              </p>
            )}
            {ws.fallbackMessage && (
              <p className="text-sm text-amber-600 mt-2">{ws.fallbackMessage}</p>
            )}
            {jobId && (
              <p className="text-xs text-gray-400 mt-2">Job: {jobId}</p>
            )}
          </div>
          <GenerationSkeleton />
        </div>
      )}

      {ws.error && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 mb-8">
          Generation failed: {ws.error}
        </div>
      )}

      {assignment.status === 'failed' && !isGenerating && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 mb-8">
          Last generation failed. Try regenerating.
        </div>
      )}

      {paper && paper.sections.length > 0 && (
        <div
          id="question-paper"
          className="space-y-8 bg-white p-6 rounded-xl"
          style={{ backgroundColor: '#ffffff' }}
        >
          <div className="flex gap-4 text-sm text-gray-500 border border-gray-200 rounded-xl p-4">
            <span>{paper.metadata.totalQuestions} questions</span>
            <span>·</span>
            <span>{paper.metadata.totalMarks} total marks</span>
            <span>·</span>
            <span>
              Easy {paper.metadata.difficultyDistribution.easy} / Medium{' '}
              {paper.metadata.difficultyDistribution.medium} / Hard{' '}
              {paper.metadata.difficultyDistribution.hard}
            </span>
          </div>

          {paper.sections.map((section) => (
            <div
              key={section.id}
              className="border border-gray-200 rounded-xl overflow-hidden"
            >
              <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
                <h2 className="text-lg font-bold text-gray-900">{section.title}</h2>
                {section.instructions && (
                  <p className="text-sm text-gray-500 mt-1">{section.instructions}</p>
                )}
              </div>
              <ol className="divide-y divide-gray-100">
                {section.questions.map((q, idx) => (
                  <li key={q.id} className="px-6 py-4">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1">
                        <p className="font-medium text-gray-900">
                          <span className="text-gray-400 mr-2">{idx + 1}.</span>
                          {q.text}
                        </p>
                        <div className="flex gap-2 mt-2">
                          <TypeTag type={q.type} />
                        </div>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <DifficultyBadge difficulty={q.difficulty} />
                        <span className="text-sm font-semibold text-gray-500 whitespace-nowrap">
                          {q.marks} marks
                        </span>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          ))}
        </div>
      )}

      {!paper && !isGenerating && assignment.status !== 'failed' && (
        <div className="text-center py-16 text-gray-500">
          No generated paper yet. Click Regenerate to create one.
        </div>
      )}
    </div>
  );
}
